services:
    paul999.mention.controller:
        class: paul999\mention\controller\main
        arguments:
            - '@user'
            - '@dbal.conn'
            - '@auth'

    paul999.mention.listener:
        class: paul999\mention\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@notification_manager'
        tags:
            - { name: event.listener }

    paul999.mention.notification.type.demo:
        class: paul999\mention\notification\type\demo
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        tags:
            - { name: notification.type }
